name : chocolatine

on : 
  push :
  pull_request :

jobs : 
  mirror : 
    name : mirror to epitech 
    runs-on : ubuntu-latest
    steps :
      - uses: action/checkout@v3
        with:
          fetch-depth: @
      - uses : pixta-dev/repository-mirroring-action@v1
        with: 
          target_repo_url: git@github.com:EpitechPromo2027/B-DOP-200-STG-2-1-chocolatine-iness.el-atouani.git
          ssh_private_key: ${{secrets.GIT_SSH_PRIVATE_KEY}}